/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admin: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admin: Admin;
    authentication: Authentication;
    user: User;
    clientAdditionalInfo: ClientAdditionalInfo;
    media: Media;
    project: Project;
    semesterProject: SemesterProject;
    semester: Semester;
    formQuestion: FormQuestion;
    form: Form;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admin: AdminSelect<false> | AdminSelect<true>;
    authentication: AuthenticationSelect<false> | AuthenticationSelect<true>;
    user: UserSelect<false> | UserSelect<true>;
    clientAdditionalInfo: ClientAdditionalInfoSelect<false> | ClientAdditionalInfoSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    project: ProjectSelect<false> | ProjectSelect<true>;
    semesterProject: SemesterProjectSelect<false> | SemesterProjectSelect<true>;
    semester: SemesterSelect<false> | SemesterSelect<true>;
    formQuestion: FormQuestionSelect<false> | FormQuestionSelect<true>;
    form: FormSelect<false> | FormSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    Home: Home;
  };
  globalsSelect: {
    Home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  user: Admin & {
    collection: 'admin';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authentication".
 */
export interface Authentication {
  id: string;
  /**
   * The email who owns this authentication
   */
  email: string;
  /**
   * The hashed user password
   */
  password?: string | null;
  /**
   * The type of authentication
   */
  provider?: 'google' | null;
  /**
   * The provider account id of the user authentication
   */
  providerAccountId?: string | null;
  /**
   * The refresh token of the user authentication
   */
  refreshToken?: string | null;
  /**
   * The access token of the user authentication, only applicable for google oauth
   */
  accessToken?: string | null;
  /**
   * The expiration time of the access token
   */
  expiresAt?: number | null;
  /**
   * The type of token
   */
  tokenType?: string | null;
  /**
   * The scope of the token
   */
  scope?: string | null;
  /**
   * The id token of the user authentication
   */
  idToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user".
 */
export interface User {
  id: string;
  email: string;
  firstName: string;
  lastName?: string | null;
  role: 'admin' | 'client' | 'student';
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientAdditionalInfo".
 */
export interface ClientAdditionalInfo {
  id: string;
  client: string | User;
  introduction?: string | null;
  affiliation?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project".
 */
export interface Project {
  id: string;
  /**
   * The name of the project, e.g. Encapsulate
   */
  name: string;
  /**
   * The description of the project, e.g. Best capstone project!
   */
  description: string;
  /**
   * The client that submitted the form
   */
  client: string | User;
  /**
   * The clients that are related to this project.
   */
  additionalClients?: (string | User)[] | null;
  attachments?: (string | Media)[] | null;
  deadline?: string | null;
  timestamp: string;
  desiredOutput: string;
  specialEquipmentRequirements: string;
  numberOfTeams: string;
  desiredTeamSkills?: string | null;
  availableResources?: string | null;
  futureConsideration: boolean;
  questionResponses?:
    | {
        question: string | FormQuestion;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formQuestion".
 */
export interface FormQuestion {
  id: string;
  /**
   * The question title, e.g. Whats your name?
   */
  question: string;
  /**
   * The description of this question provides more information about how the question can be answered! E.g. Enter a number
   */
  description: string;
  /**
   * An identifiable field name key, e.g. final_presentation_confirm
   */
  fieldName: string;
  /**
   * The question ordering ascending order, e.g. 0
   */
  order: number;
  /**
   * If the question is required or not, e.g. true
   */
  required: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semesterProject".
 */
export interface SemesterProject {
  id: string;
  number?: number | null;
  project: string | Project;
  semester: string | Semester;
  status: 'pending' | 'approved' | 'rejected';
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semester".
 */
export interface Semester {
  id: string;
  name: string;
  /**
   * Description of the semester
   */
  description?: string | null;
  deadline: string;
  startDate: string;
  endDate: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form".
 */
export interface Form {
  id: string;
  /**
   * The form name
   */
  name: string;
  /**
   * The form description
   */
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admin';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'authentication';
        value: string | Authentication;
      } | null)
    | ({
        relationTo: 'user';
        value: string | User;
      } | null)
    | ({
        relationTo: 'clientAdditionalInfo';
        value: string | ClientAdditionalInfo;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'project';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'semesterProject';
        value: string | SemesterProject;
      } | null)
    | ({
        relationTo: 'semester';
        value: string | Semester;
      } | null)
    | ({
        relationTo: 'formQuestion';
        value: string | FormQuestion;
      } | null)
    | ({
        relationTo: 'form';
        value: string | Form;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admin';
    value: string | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'admin';
    value: string | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authentication_select".
 */
export interface AuthenticationSelect<T extends boolean = true> {
  email?: T;
  password?: T;
  provider?: T;
  providerAccountId?: T;
  refreshToken?: T;
  accessToken?: T;
  expiresAt?: T;
  tokenType?: T;
  scope?: T;
  idToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user_select".
 */
export interface UserSelect<T extends boolean = true> {
  email?: T;
  firstName?: T;
  lastName?: T;
  role?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientAdditionalInfo_select".
 */
export interface ClientAdditionalInfoSelect<T extends boolean = true> {
  client?: T;
  introduction?: T;
  affiliation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project_select".
 */
export interface ProjectSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  client?: T;
  additionalClients?: T;
  attachments?: T;
  deadline?: T;
  timestamp?: T;
  desiredOutput?: T;
  specialEquipmentRequirements?: T;
  numberOfTeams?: T;
  desiredTeamSkills?: T;
  availableResources?: T;
  futureConsideration?: T;
  questionResponses?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semesterProject_select".
 */
export interface SemesterProjectSelect<T extends boolean = true> {
  number?: T;
  project?: T;
  semester?: T;
  status?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semester_select".
 */
export interface SemesterSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  deadline?: T;
  startDate?: T;
  endDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formQuestion_select".
 */
export interface FormQuestionSelect<T extends boolean = true> {
  question?: T;
  description?: T;
  fieldName?: T;
  order?: T;
  required?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form_select".
 */
export interface FormSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Home".
 */
export interface Home {
  id: string;
  aboutSection: AboutSection;
  demoSection: DemoSection;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection".
 */
export interface AboutSection {
  /**
   * The title of the about section.
   */
  title: string;
  /**
   * A about us section description.
   */
  description: string;
  button: Button;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Button".
 */
export interface Button {
  /**
   * The name of the button.
   */
  buttonName: string;
  /**
   * The link of the button.
   */
  buttonLink: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DemoSection".
 */
export interface DemoSection {
  clientDemo: ClientDemo;
  studentDemo: StudentDemo;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientDemo".
 */
export interface ClientDemo {
  /**
   * The title of the client demo section.
   */
  title: string;
  /**
   * A description of the client demo section.
   */
  description: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudentDemo".
 */
export interface StudentDemo {
  /**
   * The title of the student demo section.
   */
  title: string;
  /**
   * A description of the student demo section.
   */
  description: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  aboutSection?: T | AboutSectionSelect<T>;
  demoSection?: T | DemoSectionSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutSection_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  button?: T | ButtonSelect<T>;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Button_select".
 */
export interface ButtonSelect<T extends boolean = true> {
  buttonName?: T;
  buttonLink?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DemoSection_select".
 */
export interface DemoSectionSelect<T extends boolean = true> {
  clientDemo?: T | ClientDemoSelect<T>;
  studentDemo?: T | StudentDemoSelect<T>;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ClientDemo_select".
 */
export interface ClientDemoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StudentDemo_select".
 */
export interface StudentDemoSelect<T extends boolean = true> {
  title?: T;
  description?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}